version: "3"
volumes:
  node_module1:
  node_module2:

services:
  #     web-scratch:
  #          container_name: scratch-gui
  #          tty: true
  #          build:
  #            context: scratch
  #            dockerfile: Dockerfile
  #          ports:
  #            #   - 8601:8601  # ホストマシンのポート8000を、docker内のポート8000に接続する
  #            # - 8073:8073
  #                - 8601:8601
  #                  #-  "127.0.0.1:8601:8601"
  #          volumes: 
  #              - ./scratch/:/src:cached
  #              - node_module1:/scratch/scratch-gui/node_modules/
  #              - node_module2:/scratch/scratch-vm/node_modules/
  
  
    line-fastapi:
        container_name: line_FastAPI
        tty: true
        build:
          context: line_fastAPI/
          dockerfile: Dockerfile
        ports:
            - 8000:8000  # ホストマシンのポート8000を、docker内のポート8000に接続する
        volumes: 
            - ./line_fastAPI/:/src:cached
    db:
        image: mysql:8.0
        platform: linux/x86_64  # M1 Macの場合必要
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'  # rootアカウントをパスワードなしで作成
          MYSQL_DATABASE: 'line_api'  # 初期データベースとしてdemoを設定
          TZ: 'Asia/Tokyo'  # タイムゾーンを日本時間に設定
        volumes:
          - mysql_data:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password  # MySQL8.0ではデフォルトが"caching_sha2_password"で、ドライバが非対応のため変更
        ports:
          - 33306:3306
volumes:
  mysql_data:
