version: "3"
services:
  #    web-scratch:
  #         container_name: scratch-gui
  #         build:
  #           context: ./
  #           dockerfile: Dockerfile
  #         ports:
  #             - "8601:8601"
  #         volumes:
  #           - type: bind
  #             source:  ../ankuru-scratch-vm
  #             target: /root/scratch-vm 
  #  
  #           - type: bind
  #             source:  ../ankuru-scratch-gui
  #             target: /root/scratch-gui
  #
  #
    line-fastapi:
        container_name: line_FastAPI
        tty: true
        build:
          context: line_fastAPI/
          dockerfile: Dockerfile
        ports:
            - 8000:8000  # ホストマシンのポート8000を、docker内のポート8000に接続する
        volumes: 
            - ./line_fastAPI/:/src:cached
